name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
env:
  DOCKER_REGISTRY: rg.fr-par.scw.cloud/pinpo-images

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn

      - name: Pull from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_SAMPLE_ROOT_PAGE: ${{ secrets.DOCU_NOTION_SAMPLE_ROOT_PAGE }}
        run: yarn pull

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes from docu-notion

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REPOSITORY: pinpo-platform-documentation
        run: |
          docker build -t $DOCKER_REGISTRY/$REPOSITORY:$DOCKER_IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$REPOSITORY:$DOCKER_IMAGE_TAG

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: PINPODEV
          repositories: "infrastructure-runtime"

      - name: Check out GitOps project
        uses: actions/checkout@v4
        with:
          clean: false
          path: gitops
          repository: PINPODEV/infrastructure-runtime
          token: ${{ steps.generate-token.outputs.token }}

      - name: Write version.yaml for Demo app
        shell: bash
        env:
          VERSION_TEMPLATE: projects/platform-documentation/prod/api/version.yaml.tpl
          VERSION_OUTPUT: projects/platform-documentation/prod/api/version.yaml
        run: |
          # Change working directory
          cd gitops

          # Writing version.yaml in the appropiate folder
          sed -e 's/IMAGE_TAG/${{ env.DOCKER_IMAGE_TAG }}/g' ${{ env.VERSION_TEMPLATE }} > ${{ env.VERSION_OUTPUT }}

          # Git actions
          git config --global user.email "engineering@pinpo.ai"
          git config --global user.name "GitHub Actions"
          git add ${{ env.VERSION_OUTPUT }}
          git commit -m "update documentation version to ${{ github.sha }}"
          git push
